# Database configuration
mysql:
  type: "sqlite"
  host: "localhost"
  port: 3306
  username: "root"
  password: "example"
  database: "wallet"
  ssl: false

# Plugin configuration
resourcepack:
  enabled: true
  url: "https://github.com/Michelo11/Wallet/releases/download/v1.0/Wallet.zip"

# Wallet configuration
# Format: value: custom-model-data
banknotes:
  1: 1
  5: 5
  10: 10
  20: 20
  50: 50
  100: 100
  200: 200
  500: 500

# Wallet items configuration
atm-material: "BROWN_GLAZED_TERRACOTTA"

# Documents configuration
documents:
  id:
    material: "PAPER"
    custom-model-data: 0
    name: "&aID"
    lore:
      - "&7Name: &a%player_name%"
      - "&7Date of Birth: &a%args_0%"
    arguments: 1
  driver-license:
    material: "PAPER"
    custom-model-data: 1
    name: "&cDriver License"
    lore:
      - "&7Name: &c%player_name%"
      - "&7Vehicle Type: &c%args_0%"
    arguments: 1
    hooks:
      - "QualityArmoryVehicles2"
  passport:
    material: "PAPER"
    custom-model-data: 2
    name: "&9Passport"
    lore:
      - "&7Name: &9%player_name%"
      - "&7Nationality: &9%args_0%"
      - "&7Date of Birth: &9%args_1%"
      - "&7Gender: &9%args_2%"
      - "&7Issue Date: &9%args_3%"
      - "&7Expiry Date: &9%args_4%"
    arguments: 5
  sim:
    material: "PAPER"
    custom-model-data: 3
    name: "&2SIM Card"
    lore:
      - "&7Name: &2%player_name%"
      - "&7Number: &2%args_0%"
    arguments: 1
    hooks:
      - "Phone"

# Messages configuration
messages:
  items:
    banknote:
      name: "&6Banknote"
      lore:
        - "&7Amount: &6$%amount%"
        - "&r"
        - "&7&o(( Right click to deposit ))"
    wallet:
      name: "&uWallet"
    card:
      name: "&f&lCard"
    atm:
      name: "&eATM"
  commands:
    player-only: "&8» &cOnly players can use this command"
    no-permission: "&8» &cYou don't have permission to use this command"
    player-not-found: "&8» &cThe player is not online"
    document-type-not-found: "&8» &cThe document type is not found"
    withdraw:
      usage: "&8» &cUsage: /withdraw <amount>"
      invalid-amount: "&8» &cInvalid amount"
      insufficient-balance: "&8» &cInsufficient balance"
      success: "&8» &aYou have withdrawn &e$%amount% &afrom your wallet"
    help:
      - "&6&m-------&f&m-------&6&m-------&f&m-------&6&m-------&f&m-------"
      - "&r   &fRunning &6Wallet&f by &6Michelo11"
      - "&r"
      - "&f/wallet give <player> <type> &8»&f Give a document to a player"
      - "&f/wallet withdraw <amount> &8»&f Deposit money into your wallet"
      - "&6&m-------&f&m-------&6&m-------&f&m-------&6&m-------&f&m-------"
    give:
      usage: "&8» &cUsage: /wallet give <player> <type>"
      document-args: "&8» &cInvalid document arguments"
      success: "&8» &aYou have given &e%player% &athe &e%type% &adocument"
    getcard:
      usage: "&8» &cUsage: /wallet getcard <player>"
      success: "&8» &aYou have received the card of &e%player%&a. The pin is &e%pin%"
  listeners:
    deposit:
      success: "&8» &aYou have deposited &e$%amount% &ainto your wallet"
    vehicle:
      no-license: "&8» &cYou don't have a driver license"
    phone:
      no-sim: "&8» &cYou don't have a sim card"
  conversations:
    atm:
      pin:
        prompt: "&8» &7Please enter your pin"
        invalid: "&8» &cInvalid pin"
      amount:
        prompt: "&8» &7Please enter the amount"
        invalid: "&8» &cInvalid amount"