name: Wallet
version: '${version}'
main: me.michelemanna.wallet.WalletPlugin
api-version: '1.13'
authors: [ Michelo11 ]
website: https://michelemanna.me
commands:
  wallet:
    description: "Manage your wallet"
depend:
  - Vault
  - PlaceholderAPI
softdepend:
  - QualityArmoryVehicles2
  - Phone